strictness: veryhigh
doc-warnings: true
test-warnings: true

ignore-paths:
  - www/Adafruit_Python_GPIO/
  - www/blockly/
  - www/closure-library/
  - www/htmlcov/
  - www/docs/

pep8:
  full: true

pep257:
  run: true
  disable:
    # 1 blank line required before class docstring
    - D203
