sudo: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev
  xvfb
- sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev
  libwebp-dev
- sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv
  python-pip python-smbus
- sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev
  libreadline-dev
- sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev
  wget curl llvm
- cd www/Adafruit_Python_GPIO/
- python setup.py install
- cd ../../
install:
- pip install -r www/requirements.txt
- pip install coveralls
script:
- pushd www/docs
- make html
- popd
after_success:
- coveralls
language: python
virtualenv:
  system_site_packages: true
python:
- '2.7'
deploy:
- provider: s3
  access_key_id: AKIAILBCWVK4FYLVDQRQ
  secret_access_key:
    secure: pK5zXdus7W6jqlwMD6Bw4f098iUsYNZBq9AVLx0FvE5DQy2eh/wk8grwhZknXiBx2fg6kJrd4VWsnbR2PIMtdJT0Ixo33QeDuBcY8cFF8WOzXLTCbGqTF+7ImItlrwfdKm5/9YBX4kfAtmoQyvg9mor2OjDfMk60yTw8lhgZ5a8AYUYWvFn6TDz9b7P8X8oDo2gl7P/6hDb0ZckyK017CvAszS8rwSqFoBp7iydkWVaUB9LZsKGitzmGqXERibKX6nBu54kP990ymGd/CADswsF7yq1XOqaB2ouPzTpuJyN95OqItlcieSTWKrRKgyr1kZzE8H0uTdGQ5cxCVw+XbfT73QTHCidOVBmEsKes4yl2Vxf7+lKrSGUXO7uT9MJZKQq3LcETcRs1GWj86etGZKlclepolrvIOvhCSlCkknpTY+UiHXwWgll9XcKkuznjSdXU6qJ8u3JJJ/NU/PLBDR/DMuCyLADH8P5gShGCOy9xF7FM9QCa1SdFCs0b+4ydzH0LhuvWAPldbi8q6UHZGQ8UKYbTEGqBx7yr+kI6k4oS8Qgb4u+6e8D1b5AF1Fjz+Nag5g5AFUksDLnGUZo+VFKb03hYyIc35JJlGMuyc4V9NnfKbTHaKJp0GRiOYedOOq6FJyHYI0ez1/vx0MfZ3U+hA078gU0wvkX1s/T5De4=
  bucket: rovercode-dev-docs
  local_dir: www/docs/_build/html
  upload-dir: rovercode/development
  acl: public_read
  skip_cleanup: true
  region: us-east-2
  on:
    repo: rovercode/rovercode
    branch: docs-deploy
- provider: s3
  access_key_id: AKIAILBCWVK4FYLVDQRQ
  secret_access_key:
    secure: pK5zXdus7W6jqlwMD6Bw4f098iUsYNZBq9AVLx0FvE5DQy2eh/wk8grwhZknXiBx2fg6kJrd4VWsnbR2PIMtdJT0Ixo33QeDuBcY8cFF8WOzXLTCbGqTF+7ImItlrwfdKm5/9YBX4kfAtmoQyvg9mor2OjDfMk60yTw8lhgZ5a8AYUYWvFn6TDz9b7P8X8oDo2gl7P/6hDb0ZckyK017CvAszS8rwSqFoBp7iydkWVaUB9LZsKGitzmGqXERibKX6nBu54kP990ymGd/CADswsF7yq1XOqaB2ouPzTpuJyN95OqItlcieSTWKrRKgyr1kZzE8H0uTdGQ5cxCVw+XbfT73QTHCidOVBmEsKes4yl2Vxf7+lKrSGUXO7uT9MJZKQq3LcETcRs1GWj86etGZKlclepolrvIOvhCSlCkknpTY+UiHXwWgll9XcKkuznjSdXU6qJ8u3JJJ/NU/PLBDR/DMuCyLADH8P5gShGCOy9xF7FM9QCa1SdFCs0b+4ydzH0LhuvWAPldbi8q6UHZGQ8UKYbTEGqBx7yr+kI6k4oS8Qgb4u+6e8D1b5AF1Fjz+Nag5g5AFUksDLnGUZo+VFKb03hYyIc35JJlGMuyc4V9NnfKbTHaKJp0GRiOYedOOq6FJyHYI0ez1/vx0MfZ3U+hA078gU0wvkX1s/T5De4=
  bucket: rovercode-dev-docs
  local_dir: www/docs/_build/html
  upload-dir: rovercode/master
  acl: public_read
  skip_cleanup: true
  region: us-east-2
  on:
    repo: rovercode/rovercode
    branch: docs-deploy
notifications:
  slack:
    secure: tDLg3aPAQjoXrHQzXNUTGt758NrQKqvuHXzDVBHmOKuLWGoHh4D9BvEvjTRY3YVHPa+mz1nT4UYLDBDEcZl9mV3SjVoopLMQGpysJZhDrvBLir//eZkTmQ8/pKOVu2mmeiaw0xvRimvIW/r9boKvEGiS6QNqKitO2VFQVJX9RfFBEJg1u4vuhj6k4MIWy94Hl/6lj6yNeWEL5wUcS18R4x8nUCl8O3vaBt7RZwOkEsNj/FMja3nexdWShjOhxQuGc9TdHCpfpv8NlpNKCBlVnu7l1DKl/UzI9Qi1w4dWjWLaMDndxfpuQ2vY4ybs/UupV2Wo6Ng+m92bsJ37zPF5HGn6pi8rX02iH8J+rPRKlJq0R/McRfZ06r3k1XSFDHQrU/Fi5lIAQ7dza6i7k5JEE3AlTBJ80/MHpk9q/8uz8sTipY7V+TvNdyeuR+p5iUbwYsLIoHJotcpe8rzVOZUTW14pYodyl8PBfdgg8LmNgNwMyyWhqiC7ocxD4ltXWV7Pqq7pArHq3cts65fbFqAGfDPvt/rnV1bVnlM3aiQZE3ofVvVNB6DF7ykjqYFv6sZy1/FtKIK6pddD5I+JuFNQzMakzhJw+FI5ZeYfIra69Wu1Fo0E7t7ONXdejYooGkVZE5Gl6qyhp39S5zXAtC6pu6EklXumoSB1KXXo7MDQWgM=
