strictness: veryhigh
doc-warnings: true
test-warnings: true

pylint:
  disable:
    # Redefining name from outer scope confuses test fixtures
    - W0621
    # Too few public methods
    - R0903
    # Using the global statement
    - global-statement
    # I like fstrings
    - logging-fstring-interpolation

pep8:
  full: true
  disable:
    # bare except already covered in pylint
    - E722

pep257:
  run: true
  disable:
    # 1 blank line required before class docstring
    - D203
    # Multi-line doc should start at the first line: https://github.com/PyCQA/pydocstyle/issues/242
    - D212
